version: '3.8'
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: soar
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

