micronaut:
  application:
    name: kotlin-api-example
  server:
    port: ${PORT:8080}
    cors:
      enabled: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/soar`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:`your_username`}
    password: ${DB_PASSWORD:`your_password`}
    maximum-pool-size: 10

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false

logger:
  levels:
    com.example: INFO
    io.micronaut: INFO


